#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    get_url:
      url:  http://nexus:8081/repository/maven-releases/com/iwayq/iwayQApp/1.0-RELEASE/iwayQApp-1.0-RELEASE.war
      dest: /home/admin
      url_username: admin
      url_password: admin

  - name: Rename .war Artifact
    command: mv iwayQApp-1.0-RELEASE.war iwayq.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: iwayq
      build:
        path: /home/admin
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: parmarajay
     password: JanNew@2023

    
  - name: Push to docker hub
    docker_image:
      name: iwayq
      repository: parmarajay/irada:1.0
      push: yes
      source: local
